name:  Deployment Exercise 2
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name:  Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npx eslint --init && npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name:  Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npx eslint --init && npm run test  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: Build code
        run: npx eslint --init && npm run build
      - name: Deploy code
        run: echo "Deploying..." 
        